rollback;
begin transaction;
/*Begin Dropping Tables*/
	/*Level 2 Tables*/
		drop table if exists exerciselog;
		drop table if exists accountsubscription;
		drop table if exists exercisesubscription;
	/*Level 1 Tables*/
		drop table if exists account;
	/*Level 0 Tables*/
		drop table if exists exercise;
		drop table if exists accounttype;
/*End Dropping Tables*/

/*Begin Creating Tables*/
	/*Level 0 Tables*/
		create table accounttype (
			typeid            serial  not null unique,
			description       text    not null unique,
			constraint pk_accounttype primary key (typeid)
		);
		create table exercise (
			exerciseid        serial  not null unique,
			description       text    not null unique,
			unit              text    not null,
			constraint pk_exercise primary key (exerciseid)
		);
	/*Level 1 Tables*/
		create table account(
			userid            serial  not null unique,
			username          text    not null unique,
			"password"        text    not null,
			salt              text    not null,
			fullname          text    not null,
			email             text    not null unique,
			pictureurl        text,
			privateprofile    boolean not null,
			typeid            int     not null,
			constraint pk_account primary key (userid),
			constraint fk_accounttype foreign key (typeid) references accounttype (typeid)
		);
	/*Level 2 Tables*/
		create table accountsubscription(
			subscriberid      int     not null,
			subscribeeid      int     not null,
			constraint pk_accountsubscription primary key (subscriberid, subscribeeid),
			constraint fk_subscriber foreign key (subscriberid) references account (userid),
			constraint fk_subscribee foreign key (subscribeeid) references account (userid)
		);
		create table exerciselog(
			exerciselogid serial  not null,
			exerciseid        int     not null,
			userid            int     not null,
			units             numeric not null,
			note              text,
			occourred         date    not null,
			constraint pk_exerciselog primary key (exerciselogid),
			constraint fk_exercise foreign key (exerciseid) references exercise (exerciseid)
		);
		create table exercisesubscription(
			exercisesubscriptionid serial  not null,
			exerciseid        int     not null,
			userid            int     not null,
			constraint pk_exercisesubscription primary key (exercisesubscriptionid),
			constraint fk_exercisesub foreign key (exerciseid) references exercise (exerciseid)
		);
	
/*End Creating Tables*/

/*Begin Filling Tables*/
	/*Level 0 Tables*/
		/*accounttype*/
			insert into accounttype (description) values ('Admin');
			insert into accounttype (description) values ('User' );
		/*exercise*/
			insert into exercise (description, unit) values ('Running',     'Km');
			insert into exercise (description, unit) values ('Biking',      'Km');
			insert into exercise (description, unit) values ('Swimming',    'Km');
			insert into exercise (description, unit) values ('Curls',       'RepLbs');
			insert into exercise (description, unit) values ('Bench Press', 'RepLbs');
			insert into exercise (description, unit) values ('Deadlift',    'RepLbs');
			insert into exercise (description, unit) values ('Pushups',     'Reps');
			insert into exercise (description, unit) values ('Squats',      'Reps');
			insert into exercise (description, unit) values ('Sit Ups',     'Reps');
			insert into exercise (description, unit) values ('Pull ups',    'Reps');
	/*Level 1 Tables*/
		/*account*/
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('admin',      md5('password'||md5('admin')),      md5('admin'),      'John Smith',         'JSmith@fitnessapp.com',  null, true,  1 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('saitama',    md5('password'||md5('saitama')),    md5('Saitama'),    'Saitama',            'admin@punchman.jp',      null, false, 2 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('rock',       md5('password'||md5('rock')),       md5('Rock'),       'Dwayne Johnson',     'Rock@wwe.com',           null, false, 2 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('starlord',   md5('password'||md5('starlord')),   md5('Starlord'),   'Chris Pratt',        'cpratt@marvel.com',      null, false, 2 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('thor',       md5('password'||md5('thor')),       md5('thor'),       'Chris Hemsworth',    'chemsworth@marvel.com',  null, false, 2 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('wolverine',  md5('password'||md5('wolverine')),  md5('wolverine'),  'Hugh Jackman',       'hjackman@marvel.com',    null, false, 2 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('kimk',       md5('password'||md5('kimk')),       md5('kimk'),       'Kim kardashian',     'kim@thekardashians.com', null, false, 2 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('mwell',      md5('password'||md5('mwell')),      md5('mwell'),      'Matthew Wells',      'mwells@mail.co.uk',      null, false, 2 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('hulk',       md5('password'||md5('hulk')),       md5('hulk'),       'Hulk Hogan',         'hulk@wwe.com',           null, false, 2 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('storm',      md5('password'||md5('storm')),      md5('storm'),      'Halle Berry',        'hberry@marvel.com',      null, false, 2 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('blackwidow', md5('password'||md5('blackwidow')), md5('blackwidow'), 'Scarlett Johansson', 'sjohansson@marvel.com',  null, false, 2 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('test1',      md5('password'||md5('test1')),      md5('test1'),      'Albert Test',        'test.1@fitnessapp.com',  null, true,  2 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('test2',      md5('password'||md5('test2')),      md5('test2'),      'Brad Test',          'test.2@fitnessapp.com',  null, true,  2 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('test3',      md5('password'||md5('test3')),      md5('test3'),      'Charlene Test',      'test.3@fitnessapp.com',  null, true,  2 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('test4',      md5('password'||md5('test4')),      md5('test4'),      'Debra Test',         'test.4@fitnessapp.com',  null, true,  2 );
			insert into account (username, "password", salt, fullname, email, pictureurl, privateprofile, typeid) values ('test5',      md5('password'||md5('test5')),      md5('test5'),      'Ed Test',            'test.5@fitnessapp.com',  null, true,  2 );
	/*Level 2 Tables*/
		/*accountsubscription*/
			insert into accountsubscription (subscriberid, subscribeeid) values (1, 2);
			insert into accountsubscription (subscriberid, subscribeeid) values (1, 3);
			insert into accountsubscription (subscriberid, subscribeeid) values (3, 2);
			insert into accountsubscription (subscriberid, subscribeeid) values (4, 2);
			insert into accountsubscription (subscriberid, subscribeeid) values (5, 2);
			insert into accountsubscription (subscriberid, subscribeeid) values (6, 2);
			insert into accountsubscription (subscriberid, subscribeeid) values (8, 2);
			insert into accountsubscription (subscriberid, subscribeeid) values (9, 2);
			insert into accountsubscription (subscriberid, subscribeeid) values (9, 3);
			insert into accountsubscription (subscriberid, subscribeeid) values (10,2);
			insert into accountsubscription (subscriberid, subscribeeid) values (11,2);
			insert into accountsubscription (subscriberid, subscribeeid) values (12,2);
			insert into accountsubscription (subscriberid, subscribeeid) values (13,2);
			insert into accountsubscription (subscriberid, subscribeeid) values (14,2);
			insert into accountsubscription (subscriberid, subscribeeid) values (15,2);
			insert into accountsubscription (subscriberid, subscribeeid) values (16,2);
			insert into accountsubscription (subscriberid, subscribeeid) values (11,3);
			insert into accountsubscription (subscriberid, subscribeeid) values (12,3);
			insert into accountsubscription (subscriberid, subscribeeid) values (13,3);
			insert into accountsubscription (subscriberid, subscribeeid) values (14,3);
			insert into accountsubscription (subscriberid, subscribeeid) values (15,3);
			insert into accountsubscription (subscriberid, subscribeeid) values (11,4);
			insert into accountsubscription (subscriberid, subscribeeid) values (12,4);
			insert into accountsubscription (subscriberid, subscribeeid) values (13,4);
			insert into accountsubscription (subscriberid, subscribeeid) values (14,4);
			insert into accountsubscription (subscriberid, subscribeeid) values (11,5);
			insert into accountsubscription (subscriberid, subscribeeid) values (12,5);
			insert into accountsubscription (subscriberid, subscribeeid) values (13,5);
			insert into accountsubscription (subscriberid, subscribeeid) values (11,6);
			insert into accountsubscription (subscriberid, subscribeeid) values (12,6);
			insert into accountsubscription (subscriberid, subscribeeid) values (11,7);
		/*exerciselog*/
			/*the admin*/
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 1,  2.5,  null, '2019-02-01' );
			/*One Punch Man*/
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-07' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-07' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-07' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-07' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-14' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-14' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-14' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-14' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-21' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-21' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-21' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-21' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (7, 2,  100,  null, '2019-02-28' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 2,  100,  null, '2019-02-28' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 2,  100,  null, '2019-02-28' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 2,  10,   null, '2019-02-28' );
			/*The Rock*/
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  5,    null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1000, null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  36,   null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  2400, null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  60,   null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  8,    null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1500, null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  24,   null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  1800, null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  240,  null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  3,    null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  3000, null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  48,   null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  3500, null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  15,   null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  8,    null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1500, null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  80,   null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  900,  null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  300,  null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  5,    null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1000, null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  36,   null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  2400, null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  60,   null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  20,   null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  4000, null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  12,   null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  4000, null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  90,   null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  5,    null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1000, null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  36,   null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  2400, null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  60,   null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  8,    null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1500, null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  24,   null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  1800, null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  240,  null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  3,    null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  3000, null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  48,   null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  3500, null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  15,   null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  8,    null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1500, null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  80,   null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  900,  null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  300,  null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  5,    null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1000, null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  36,   null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  2400, null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  60,   null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  20,   null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  4000, null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  12,   null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  4000, null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  90,   null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  5,    null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1000, null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  36,   null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  2400, null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  60,   null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  8,    null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1500, null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  24,   null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  1800, null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  240,  null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  3,    null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  3000, null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  48,   null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  3500, null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  15,   null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  8,    null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1500, null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  80,   null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  900,  null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  300,  null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  5,    null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1000, null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  36,   null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  2400, null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  60,   null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  20,   null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  4000, null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  12,   null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  4000, null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  90,   null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  5,    null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1000, null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  36,   null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  2400, null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  60,   null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  8,    null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1500, null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  24,   null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  1800, null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  240,  null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  3,    null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  3000, null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  48,   null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  3500, null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  15,   null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  8,    null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1500, null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  80,   null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  900,  null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  300,  null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  5,    null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  1000, null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  36,   null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  2400, null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  60,   null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 3,  20,   null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 3,  4000, null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 3,  12,   null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 3,  4000, null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 3,  90,   null, '2019-02-27' );
			/*Starlord*/
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 1.8,   null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 1.9,   null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 1.0,   null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 1.1,   null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 1.2,   null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 1.3,   null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 1.4,   null, '2019-02-07' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 1.5,   null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 1.6,   null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 1.7,   null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 1.8,   null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 1.9,   null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 2.0,   null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 2.1,   null, '2019-02-14' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 2.2,   null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 2.3,   null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 2.4,   null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 2.5,   null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 2.6,   null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 2.7,   null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 2.8,   null, '2019-02-21' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 2.9,   null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 3.0,   null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 3.1,   null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 3.2,   null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 3.3,   null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 3.4,   null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 4, 3.5,   null, '2019-02-28' );
			/*Thor*/
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-07' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-14' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-21' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 5,  10,   null, '2019-02-28' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  750,  null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  740,  null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  760,  null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  780,  null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  790,  null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  710,  null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  700,  null, '2019-02-07' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  730,  null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  750,  null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  760,  null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  770,  null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  750,  null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  780,  null, '2019-02-14' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  740,  null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  750,  null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  740,  null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  770,  null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  720,  null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  780,  null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  760,  null, '2019-02-21' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  750,  null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  770,  null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  750,  null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  750,  null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  790,  null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 5,  800,  null, '2019-02-28' );
			/*Jacked Man*/
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-07' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-14' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-21' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 6,  10,   null, '2019-02-28' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  650,  null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  660,  null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  680,  null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  690,  null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  610,  null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  600,  null, '2019-02-07' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  630,  null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  630,  null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  650,  null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  660,  null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  670,  null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  650,  null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  680,  null, '2019-02-14' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  650,  null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  640,  null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  670,  null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  620,  null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  680,  null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  660,  null, '2019-02-21' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  650,  null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  650,  null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  670,  null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  650,  null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  650,  null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 6,  700,  null, '2019-02-28' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  650,  null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  660,  null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  680,  null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  690,  null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  610,  null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  600,  null, '2019-02-07' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  630,  null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  630,  null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  650,  null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  660,  null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  670,  null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  650,  null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  680,  null, '2019-02-14' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  650,  null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  640,  null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  670,  null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  620,  null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  680,  null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  660,  null, '2019-02-21' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  650,  null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  650,  null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  670,  null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  650,  null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  650,  null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 6,  700,  null, '2019-02-28' );
			/*KimK*/
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (2, 7,  1,    null, '2019-02-28' );
			/*runnerguy*/
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.3, null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.4, null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.5, null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.6, null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.5, null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.6, null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.2, null, '2019-02-07' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.6, null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.9, null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.1, null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  48.8, null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  52.1, null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.6, null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.7, null, '2019-02-14' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.8, null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.3, null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.3, null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.2, null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.2, null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.3, null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.4, null, '2019-02-21' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.5, null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.7, null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.1, null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.2, null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.6, null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.7, null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 8,  50.2, null, '2019-02-28' );
			/*Hulk Hogan*/
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  5,    null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  100,  null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  36,   null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  240,  null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  6,    null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  8,    null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  150,  null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  24,   null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  180,  null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  24,   null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  3,    null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  300,  null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  48,   null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  350,  null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  15,   null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  8,    null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  150,  null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  8,    null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  90,   null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  30,   null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  5,    null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  100,  null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  36,   null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  240,  null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  6,    null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  2,    null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  400,  null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  12,   null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  400,  null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  9,    null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  5,    null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  100,  null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  36,   null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  240,  null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  6,    null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  8,    null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  150,  null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  24,   null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  180,  null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  24,   null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  3,    null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  300,  null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  48,   null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  350,  null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  15,   null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  8,    null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  150,  null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  8,    null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  90,   null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  30,   null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  5,    null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  100,  null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  36,   null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  240,  null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  6,    null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  2,    null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  400,  null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  12,   null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  400,  null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  9,    null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  5,    null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  100,  null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  36,   null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  240,  null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  6,    null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  8,    null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  150,  null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  24,   null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  180,  null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  24,   null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  3,    null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  300,  null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  48,   null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  350,  null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  15,   null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  8,    null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  150,  null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  8,    null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  90,   null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  30,   null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  5,    null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  100,  null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  36,   null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  240,  null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  6,    null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  2,    null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  400,  null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  12,   null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  400,  null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  9,    null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  5,    null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  100,  null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  36,   null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  240,  null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  6,    null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  8,    null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  150,  null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  24,   null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  180,  null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  24,   null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  3,    null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  300,  null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  48,   null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  350,  null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  15,   null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  8,    null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  150,  null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  8,    null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  90,   null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  30,   null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  5,    null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  100,  null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  36,   null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  240,  null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  6,    null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (1, 9,  2,    null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (5, 9,  400,  null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (8, 9,  12,   null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (6, 9,  400,  null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (4, 9,  9,    null, '2019-02-27' );
			/*Storm*/
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-07' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-14' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-21' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 10, 100,  null, '2019-02-28' );
			/*Black Widow*/
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-01' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-02' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-03' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-04' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-05' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-06' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-07' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-08' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-09' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-10' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-11' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-12' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-13' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-14' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-15' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-16' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-17' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-18' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-19' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-20' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-21' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-22' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-23' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-24' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-25' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-26' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-27' );
				insert into exerciselog (exerciseid, userid, units, note, occourred) values (9, 11, 200,  null, '2019-02-28' );
		/*accountsubscription*/
			insert into exercisesubscription (exerciseid, userid) values (1,  1  );
			insert into exercisesubscription (exerciseid, userid) values (2,  1  );
			insert into exercisesubscription (exerciseid, userid) values (3,  1  );
			insert into exercisesubscription (exerciseid, userid) values (4,  1  );
			insert into exercisesubscription (exerciseid, userid) values (5,  1  );
			insert into exercisesubscription (exerciseid, userid) values (6,  1  );
			insert into exercisesubscription (exerciseid, userid) values (7,  1  );
			insert into exercisesubscription (exerciseid, userid) values (8,  1  );
			insert into exercisesubscription (exerciseid, userid) values (9,  1  );
			insert into exercisesubscription (exerciseid, userid) values (10, 1  );
			insert into exercisesubscription (exerciseid, userid) values (1,  2  );
			insert into exercisesubscription (exerciseid, userid) values (7,  2  );
			insert into exercisesubscription (exerciseid, userid) values (8,  2  );
			insert into exercisesubscription (exerciseid, userid) values (9,  2  );
			insert into exercisesubscription (exerciseid, userid) values (1,  3  );
			insert into exercisesubscription (exerciseid, userid) values (4,  3  );
			insert into exercisesubscription (exerciseid, userid) values (5,  3  );
			insert into exercisesubscription (exerciseid, userid) values (6,  3  );
			insert into exercisesubscription (exerciseid, userid) values (8,  3  );
			insert into exercisesubscription (exerciseid, userid) values (1,  4  );
			insert into exercisesubscription (exerciseid, userid) values (1,  5  );
			insert into exercisesubscription (exerciseid, userid) values (5,  5  );
			insert into exercisesubscription (exerciseid, userid) values (1,  6  );
			insert into exercisesubscription (exerciseid, userid) values (4,  6  );
			insert into exercisesubscription (exerciseid, userid) values (5,  6  );
			insert into exercisesubscription (exerciseid, userid) values (2,  7  );
			insert into exercisesubscription (exerciseid, userid) values (1,  8  );
			insert into exercisesubscription (exerciseid, userid) values (1,  9  );
			insert into exercisesubscription (exerciseid, userid) values (4,  9  );
			insert into exercisesubscription (exerciseid, userid) values (5,  9  );
			insert into exercisesubscription (exerciseid, userid) values (6,  9  );
			insert into exercisesubscription (exerciseid, userid) values (8,  9  );
			insert into exercisesubscription (exerciseid, userid) values (9,  10 );
			insert into exercisesubscription (exerciseid, userid) values (9,  11 );
			insert into exercisesubscription (exerciseid, userid) values (10, 12 );
			insert into exercisesubscription (exerciseid, userid) values (10, 13 );
			insert into exercisesubscription (exerciseid, userid) values (10, 14 );
			insert into exercisesubscription (exerciseid, userid) values (10, 15 );
			insert into exercisesubscription (exerciseid, userid) values (10, 16 );
/*End Filling Tables*/
commit;